# Generated by Django 4.1.2 on 2022-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
