# Generated by Django 4.1.2 on 2022-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_restaurants_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='location',
            field=models.URLField(default='https://sfdc.com', max_length=300),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
