# Generated by Django 4.1.2 on 2022-11-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_restaurants_location_restaurants_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
