# Generated by Django 4.1.2 on 2022-11-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_restaurants_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='number',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
