# Generated by Django 4.1.2 on 2022-11-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_remove_restaurants_location_remove_restaurants_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='slug',
        ),
    ]
