# Generated by Django 4.1.2 on 2022-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_details_remove_restaurants_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('food', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
