# Generated by Django 4.1.2 on 2022-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
