# Generated by Django 4.1.2 on 2022-11-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_delete_user_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
